### ISSUE TITLE
Installation of standard

### ISSUE THREAD

**Issue by kandrejevs** [cytopia/docker-phpcs#4]
Hi,
I'm having trouble installing magento2 standard to use with phpstorm.
I have set phpcs interpreter as this container and under inspections standards like PSR1, ZEND and others work fine, but if under inspections I add installed path to ruleset.xml located in vendor folder I get `coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend` error.

**Comment by cytopia** [comment]
@kandrejevs can you point me to the website where this standard can be found/downloaded. I might have to integrate it into the container.

**Comment by kandrejevs** [comment]
in this particular case I'm trying to set this as standard : https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/framework/Magento/ruleset.xml

**Comment by cytopia** [comment]
When you mount the standard into the Docker container, you need to ensure that the file it requires is also present at that specific location: https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/framework/Magento/ruleset.xml#L10

Alternatively adjust the line and mount both from the same directory.

**Comment by Pedr0Rocha** [comment]
@cytopia I have my own .xml ruleset, is there an easy way to run your container using my rules as default?

Good job btw, very easy to use.

**Comment by biggianteye** [comment]
When using a custom standard, you can tell phpcs where it lives by setting `installed_paths`. The example below uses phpcs installed via composer:

```
# Set the value. This gets saved to a conf file.
$ ./vendor/bin/phpcs --config-set installed_paths foo
Using config file: <...>/vendor/squizlabs/php_codesniffer/CodeSniffer.conf

Config value "installed_paths" added successfully

# Confirm the value
$ ./vendor/bin/phpcs --config-show installed_paths
Using config file: <...>/vendor/squizlabs/php_codesniffer/CodeSniffer.conf

installed_paths: foo

# Show the contents of the config file.
$ cat vendor/squizlabs/php_codesniffer/CodeSniffer.conf
<?php
 $phpCodeSnifferConfig = array (
  'installed_paths' => 'foo',
)
?>
```

This docker image does not use composer to install phpcs. Instead it uses a `.phar` file stored in `/usr/bin`. phpcs will look for the config file `/usr/bin/CodeSniffer.conf`. One way to be able to use a custom standard with this image would be to have a `CodeSniffer.conf` in your project and mount it.

Using docker:

```
$ docker run --rm -v $(pwd):/data -v CodeSniffer.conf:/usr/bin/CodeSniffer.conf cytopia/phpcs .
```

Using docker-compose:

```yaml
phpcs:
  image: cytopia/phpcs
  volumes:
    - .:/data
    - CodeSniffer.conf:/usr/bin/CodeSniffer.conf
```

```
$ docker-compose run --rm phpcs .
```

Note that I haven't tested any of this, so it might need adjusting.

**Comment by cytopia** [comment]
@biggianteye thanks for the code snippet, it's probably a good idea to add this as an example to the Readme.

@kandrejevs can you confirm that this works fine for you?

**Comment by gerasart** [comment]
cd vendor && rm -rf magento/

**Comment by Juuuke** [comment]
Hey, 

It works great using CodeSniffer.conf to specify rules and standard to use. But how to create a specific standard using ruleset.xml maybe and register it ? So I can add "standard' => "myStandard" in CodeSniffer.conf ?

**Comment by maxgalbu** [comment]
This is what i've done to have multiple rulesets without having to install them locally:

```dockerfile
FROM cytopia/phpcs:3-php8.1

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

RUN composer require --dev sirbrillig/phpcs-variable-analysis \
    && composer require --dev wp-coding-standards/wpcs:^3.0

COPY CodeSniffer.conf /usr/bin/CodeSniffer.conf
```

CodeSniffer.conf
```php
<?php

$phpCodeSnifferConfig = [
  'installed_paths' => implode(",", [
        "/data/vendor/sirbrillig/phpcs-variable-analysis",
        "/data/vendor/phpcsstandards/phpcsutils",
        "/data/vendor/phpcsstandards/phpcsextra",
        "/data/vendor/wp-coding-standards/wpcs",
    ]),
];
```

Then 
```
# Build:
$ docker build . -t my/phpcs

# Run:
$ docker run --rm my/phpcs -i
The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz, Zend, VariableAnalysis, WordPress, WordPress-Core, WordPress-Docs and WordPress-Extra
```
